version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn spaceag.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: mdillon/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  nginx: 
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports: 
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

